//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ev_WCF_WApp_TFile.SRef_TextFile {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TFData", Namespace="http://schemas.datacontract.org/2004/07/Ev_WCF_SLib_TFile")]
    [System.SerializableAttribute()]
    public partial class TFData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRef_TextFile.ICL_TextFile")]
    public interface ICL_TextFile {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICL_TextFile/Get_TFData", ReplyAction="http://tempuri.org/ICL_TextFile/Get_TFDataResponse")]
        Ev_WCF_WApp_TFile.SRef_TextFile.TFData[] Get_TFData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICL_TextFile/Get_TFData", ReplyAction="http://tempuri.org/ICL_TextFile/Get_TFDataResponse")]
        System.Threading.Tasks.Task<Ev_WCF_WApp_TFile.SRef_TextFile.TFData[]> Get_TFDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICL_TextFile/Get_TFData_WForms", ReplyAction="http://tempuri.org/ICL_TextFile/Get_TFData_WFormsResponse")]
        Ev_WCF_WApp_TFile.SRef_TextFile.TFData[] Get_TFData_WForms(string FUpLoad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICL_TextFile/Get_TFData_WForms", ReplyAction="http://tempuri.org/ICL_TextFile/Get_TFData_WFormsResponse")]
        System.Threading.Tasks.Task<Ev_WCF_WApp_TFile.SRef_TextFile.TFData[]> Get_TFData_WFormsAsync(string FUpLoad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICL_TextFile/Get_LongestPeriod", ReplyAction="http://tempuri.org/ICL_TextFile/Get_LongestPeriodResponse")]
        Ev_WCF_WApp_TFile.SRef_TextFile.TFData[] Get_LongestPeriod(Ev_WCF_WApp_TFile.SRef_TextFile.TFData[] LTFData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICL_TextFile/Get_LongestPeriod", ReplyAction="http://tempuri.org/ICL_TextFile/Get_LongestPeriodResponse")]
        System.Threading.Tasks.Task<Ev_WCF_WApp_TFile.SRef_TextFile.TFData[]> Get_LongestPeriodAsync(Ev_WCF_WApp_TFile.SRef_TextFile.TFData[] LTFData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICL_TextFileChannel : Ev_WCF_WApp_TFile.SRef_TextFile.ICL_TextFile, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CL_TextFileClient : System.ServiceModel.ClientBase<Ev_WCF_WApp_TFile.SRef_TextFile.ICL_TextFile>, Ev_WCF_WApp_TFile.SRef_TextFile.ICL_TextFile {
        
        public CL_TextFileClient() {
        }
        
        public CL_TextFileClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CL_TextFileClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CL_TextFileClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CL_TextFileClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ev_WCF_WApp_TFile.SRef_TextFile.TFData[] Get_TFData() {
            return base.Channel.Get_TFData();
        }
        
        public System.Threading.Tasks.Task<Ev_WCF_WApp_TFile.SRef_TextFile.TFData[]> Get_TFDataAsync() {
            return base.Channel.Get_TFDataAsync();
        }
        
        public Ev_WCF_WApp_TFile.SRef_TextFile.TFData[] Get_TFData_WForms(string FUpLoad) {
            return base.Channel.Get_TFData_WForms(FUpLoad);
        }
        
        public System.Threading.Tasks.Task<Ev_WCF_WApp_TFile.SRef_TextFile.TFData[]> Get_TFData_WFormsAsync(string FUpLoad) {
            return base.Channel.Get_TFData_WFormsAsync(FUpLoad);
        }
        
        public Ev_WCF_WApp_TFile.SRef_TextFile.TFData[] Get_LongestPeriod(Ev_WCF_WApp_TFile.SRef_TextFile.TFData[] LTFData) {
            return base.Channel.Get_LongestPeriod(LTFData);
        }
        
        public System.Threading.Tasks.Task<Ev_WCF_WApp_TFile.SRef_TextFile.TFData[]> Get_LongestPeriodAsync(Ev_WCF_WApp_TFile.SRef_TextFile.TFData[] LTFData) {
            return base.Channel.Get_LongestPeriodAsync(LTFData);
        }
    }
}
